<?php use_script('/modules/minicore-files/static/file-dropbox.js') ?>
<?php use_css($styleUrl) ?>
<div id="<?= $options['containerId'] ?>" class="file-dropbox-container">
    <div class="file-dropbox">
        <i class="fas fa-upload"></i>
        <?= text('files', 'drop_files_here_or') ?> <a class="file-dropbox-upload-link"><?= text('files', 'click_to_upload') ?></a>!
        <input type="file" name="file" style="display: none">
    </div>
    <ul class="file-dropbox-list"></ul>
</div>

<?php append_block('scripts') ?>
<script>createFileDropbox(<?= json_encode($options) ?>, <?= $callbacks ?>);</script>
<?php end_block() ?>